### PR TITLE
Run `yarn test` as well when testing creation of new project

### PR DESCRIPTION
**Pull request by vgrichina**

### CODE REVIEW

**Comment by vgrichina** [comment]
@icerove did you look into test failures on CI?

**Comment by icerove** [comment]
No, I don't have time today.

**Comment by icerove** [comment]
I will check it on Monday

**Comment by icerove** [comment]
we do not have any test script in blank_template, so `yarn test` is not effective

**Comment by vgrichina** [comment]
@icerove 

> we do not have any test script in blank_template, so yarn test is not effective

1) `blank_template` would benefit from having `yarn test`
2) Tests didn't pass in React template for unclear reason.

**Comment by icerove** [comment]
fix the test

**Pull request merged**
